### ISSUE TITLE
Code block display using Markdown

### ISSUE THREAD

**Issue by h-enk** [tbolt/boltcss#17]
## Issue

When using a Markdown processor (like e.g. Hugo), the following code block:

````md
```bash
npm create hyas@latest
```
````

gets rendered into `html` like so:

```html
<pre><code class="language-bash">npm create hyas@latest
</code></pre>
```

and displays as:

![Snag_5841e32](https://user-images.githubusercontent.com/3902872/208857006-053c6cb1-d476-465b-8a27-a0c8695adc8f.png)

Looks like the extra border was not intended.

## Solution

Possible solution is to update `pre > code` to something like:

```css
pre > code {
  padding: 8px 6px;
  border: 0;
  display: block;
  overflow-x: auto;
}
```

![Snag_58dadc4](https://user-images.githubusercontent.com/3902872/208859101-eb614850-99f9-4183-8aeb-f0ab53da3d13.png)

## Resources

- [Code Blocks](https://www.markdownguide.org/basic-syntax/#code-blocks)
