### ISSUE TITLE
Label not work using text-align:center;

### ISSUE THREAD

**Issue by rexwithluv** [tbolt/boltcss#26]
Actual file style.css 
```css
.container {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
}

.centered-box {
  padding: 20px;
  background-color: rgba(255, 255, 255, 0.2);
  border-radius: 15px;
  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
  max-width: 400px;
  width: 100%;
  text-align: center;
  margin: auto;
}
```

![imagen](https://github.com/user-attachments/assets/cebfb3e6-e8fd-4a76-93af-273d68a8b97c)

If you use any other typical text label, it will be centered together with the inputs, but not with `<label>`. The easiest way to solve it is to write on the css `label{display: inline-block;}`

Anyway, I'm not sure if this is a bug or something done on purpose. 

If add `label {display:inline-block;}`

![imagen](https://github.com/user-attachments/assets/cbca94d3-e571-47ea-9442-e8f2eadf21e3)
