### ISSUE TITLE
Add hover/focus state to links

### ISSUE THREAD

**Issue by tbolt** [tbolt/boltcss#9]

**Comment by bueltge** [comment]
Would you have a simple submission like this?

```css
a:active {
    filter: brightness(var(--active-brightness));
    text-decoration: none;
}

a:hover {
    filter: brightness(var(--hover-brightness));
    text-decoration: none;
}

a:focus {
    filter: brightness(var(--focus-brightness));
    text-decoration: none;
}
```
